title: Sharaal's Blog
description: Yet another Blog by and for AI Enthusiasts and Developers
author: Sharaal
email: blog@sharaal.de
github_username: Sharaal
theme: minima
show_excerpts: true
excerpt_separator: <!--more-->
gems:
- jekyll-feed
